KERNEL_SIZE: 101
img_size: [256, 384]
init_samples: 1
max_samples: 150
nepoch: 8001
init_method: "random"
densification_interval: 300
learning_rate: 0.01
img_name: "input/tulip.JPG"
show_comparison: False
display_interval: 100
gradient_threshold: 0.002
gaussian_threshold: 0.002
loss_fn: "l1_ssim"
display_loss: False
sched_type: "exponential"
schedule_max: 256
schedule_interval: 1000
